version: '3.9'

services:
  mysql:
      image: mysql
      container_name: mysql
      environment:
        - "MYSQL_DATABASE=orderManagement"
        - "MYSQL_USER=user"
        - "MYSQL_PASSWORD=root"
        - "MYSQL_ROOT_PASSWORD=root"
      ports:
        - "127.0.0.1:3308:3309"
      volumes:
        - C:\Users\PC\Videos\Captures:/var/lib/mysql
  app:
    image: 'springboot-restful-webservices:latest'
    container_name: springboot-mysql-container
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/orderManagement?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=9090
    ports:
      - "127.0.0.1:9090:9091"